apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "dotnet-demoapp"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "dotnet-demoapp"
    spec:
      containers:
        - name: "dotnet-demoapp"
          image: "gerwaldoacr.azurecr.io/apps/dotnet-demoapp"
          ports:
          - containerPort: 80
