apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: K8-Demo-App
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: dotnet-demoapp
          image: apps/dotnet-demoapp
          ports:
          - containerPort: 80
