apiVersion : apps/v1
kind: Deployment
metadata:
  name: dotnet-demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-demoapp
  template:
    metadata:
      labels:
        app: dotnet-demoapp
    spec:
      containers:
        - name: dotnet-demoapp
          image: apps/dotnet-demoapp
          ports:
          - containerPort: 80
