apiVersion : apps/v1
kind: Deployment
metadata:
  name: K8-Demo-App
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: dotnet-demoapp
          image: apps/dotnet-demoapp
          ports:
          - containerPort: 80
