apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "goaks"
    labels:
        app: "goaks"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: goaks056b-goaks.9d8a1bf6e21740a9a39f.westeurope.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "goaks"
                servicePort: 80