image:
  pullPolicy: Always

service:
  targetPort: 5000

secretEnv:
  Weather__ApiKey:
    secretName: dotnet-demoapp
    secretKey: weatherKey
  AzureAd__ClientSecret:
    secretName: dotnet-demoapp
    secretKey: aadAppSecret

env: 
  ApplicationInsights__InstrumentationKey: 95ca3185-c8b8-4789-be9c-c85b11340ec1
  AzureAd__ClientId: 3584ac39-1ab1-4fe6-a3dd-4b2fbedc9d7d
  AzureAd__Instance: https://login.microsoftonline.com/
  AzureAd__TenantId: common
  AzureAd__CallbackPath: /signin-oidc

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#  tls: 
#    enabled: true
#    secretName: kube-benco-io-cert
